import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Card } from '../components/card'
import { Header } from '../components/header'
import { ICard } from '../shared/interfaces/ICard'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const mock: ICard= {
    title: 'Placeholder',
    description: 'This is a very big and good description',
    rating: 5,
    imageUrl: 'https://i.imgur.com/q0Pg7nj_d.jpg?maxwidth=520&shape=thumb&fidelity=high'
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header User='John Doe' Description='Very nice description' url=''/> 
      <main className={styles.main}>


        

        <div >
        <Card {...mock}></Card>
        <Card {...mock}></Card>
        <Card {...mock}></Card>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
